### ISSUE TITLE
Issue on link travel times on DTA model

### ISSUE THREAD

**Issue by zhilee2019** [p-ortmann/dyntapy#5] opened 2022-08-20 13:57 UTC
Hi Paul:

I susscessfully ran DTA on Sioux Falls network.  The link flow results seem correct for me since it looks similar to my demand model. However, the link cost seems not corret. It show as the following figure .
![flow_results](https://user-images.githubusercontent.com/57939384/185749455-7d85c07f-b200-492a-8e49-dd4f777268b0.png)
Then, I print np.min(link cost) , it appears "nan" values as the figure below. Is it normal? 
![link_cost](https://user-images.githubusercontent.com/57939384/185749547-609e741e-36b6-449c-945d-d6c7d6398d3b.png)

**Comment by p-ortmann** [comment] 2022-08-21 12:15
Hi Zhi,
thanks for reporting!

That looks like a bug, but it's hard to say without more details about the configuration of the network and demand you're looking into. If you supply a minimal reproducer, that is a script that builds and runs the assignment, I'd be happy to take a look.

**Comment by zhilee2019** [comment] 2022-08-22 02:11
##Here is a minmal example. I simplified demand model with simple random od. By the way, if you make inner_city_centroid_spacing=2000, the link cost won't change at all. I want some changes varying with time. 


from dyntapy.supply_data import relabel_graph, road_network_from_place
from dyntapy.demand_data import add_centroids, auto_configured_centroids
from dyntapy.visualization import show_network
from dyntapy import get_toy_network
from dyntapy.demand_data import od_graph_from_matrix
import numpy as np
from dyntapy.assignments import DynamicAssignment
from dyntapy.demand import SimulationTime
from dyntapy.demand import DynamicDemand
import matplotlib.pyplot as plt

## Genrate Graph
inner_city_centroid_spacing=2500

g=get_toy_network('siouxfalls')
for u,v in list(g.edges):
    g[u][v]['free_speed']=np.clip(g[u][v]['free_speed'],a_min=50,a_max=80)

for u,v in list(g.edges):
    g[u][v]['capacity']=np.clip(g[u][v]['capacity'],a_min=1800,a_max=2000)

    #g ,_= relabel_graph(g,return_inverse=True)
centroidx,centroidy, names, place_tags = auto_configured_centroids('sioux falls', buffer_dist_close=5000,
                                                    buffer_dist_extended=5000,
                                                    inner_city_centroid_spacing=inner_city_centroid_spacing)

connector_type = 'link'
k=1
g = add_centroids(g, centroidx, centroidy, k=k, method=connector_type,name=names, place=place_tags)
g = relabel_graph(g)
show_network(g, euclidean=True)

###
#24 hour flow with daily traffic pattern.
one_day=[2634,1281,764,638,723,1414,4092,9306,13902,12955,10756,10460,11414,11972,11832,13339,15396,16984,16790,13106,9722,8195,6021,3899]

# genrate od flow.   
def random_xy(flow):
    num_centroids=len(centroidx)
    x=np.random.randint(num_centroids,size=flow)
    y=np.random.randint(num_centroids,size=flow)
    z=list(zip(x,y))
    od_matrix=np.zeros((num_centroids,num_centroids))
    for o,d in z:
        od_matrix[o][d]+=1
    od_matrix=od_graph_from_matrix(od_matrix, centroidx, centroidy)
    return od_matrix

#create od demand every 6 minutes

min_flow=[]
od_matrix=[]
interval=6  ##every 6 minutes 
for f in one_day:
    p=f//(60//interval) 
    minf=list(np.random.poisson(p,(60//interval))) ## for hourly flow, create 10*6min flow 
    min_flow+=minf
    min_od=[random_xy(j) for j in minf]
    od_matrix+=min_od
insertion_times=np.arange(0,24,interval/60)

## Run Simulation
dynamic_demand = DynamicDemand(od_matrix, insertion_times=insertion_times)
simulation_time = SimulationTime(np.float32(0.0), np.float32(24), step_size=1/12)
assignment = DynamicAssignment(g, dynamic_demand, simulation_time)
#flows, link_costs=aon(g, dynamic_demand, simulation_time)
method='incremental_assignment'#'i_ltm_aon'
r = assignment.run(method=method)


##Plot and print result
link_cost=np.mean(r.link_costs,axis=1)*60
for i in range(r.link_costs.shape[1]):
    plt.plot(link_cost)
np.min(res.link_costs,axis=0)

**Comment by p-ortmann** [comment] 2022-08-22 10:05
The dynamic assignment routines are defined on the link-turn graph and require turn connectors, as explained in the docs on add_centroids:  https://dyntapy.readthedocs.io/en/latest/source/dyntapy.html#module-dyntapy.demand_data 

If I run your example with turn connectors I do not get any NaN values.

I've added a conditional now to raise an error if someone tries to invoke the DTA routines on a graph with link connectors. ( https://github.com/p-ortmann/dyntapy/commit/635244d96af72c084cb67a713f0fb1d3eb821e3a )

Hope this helps!

**Comment by zhilee2019** [comment] 2022-08-22 11:04
Hi Paul:

Now, I changed the connector type. There are two problems. Firstly, when you reduce centorids or increase traffic, the Nan issue still ocurred, Secondly, I always get assertion error after updating the code you just updated.

Best

**Comment by p-ortmann** [comment] 2022-08-22 11:29
Are you pulling directly from the repository? 
Which version of dyntapy is installed?

You can easily verify: 
```
import dyntapy
dyntapy.__version__
```

The assertion error indicates that you do not have turn connectors. 
You need to pass method = 'turn' to add_centroids

Do you see the turn connectors when you visualize the network ? There should be two links from a centroid to a network node instead of one.

**Comment by zhilee2019** [comment] 2022-08-22 13:04
Hi Paul:

I just update all files. It works well with turn connectors. However, the second problem still remains.

My version is 0.2.2.  Here is the network. The connector is truly "turn". 
![1661173391742](https://user-images.githubusercontent.com/57939384/185927869-7088851a-eee4-492d-869b-91161fd43be6.png)

If you set "one_day" traffic value as the following. You will get NaN

<pre>
one_day=np.array([2957,1529,930,775,773,1724,4577,10525,15702,14495,12121,11816,12799,13703,13566,15016,17584,19258,19283,14928,11333,9183,6911,4595])
<\pre>

In this scenario,  the daily traffic is about 250000
![1661173361419](https://user-images.githubusercontent.com/57939384/185927903-e35a2522-221c-4397-b17e-cb547cde0ef5.png)

**Comment by p-ortmann** [comment] 2022-08-22 14:53
I have had a look into it and found the error. Seems to happen if there is congestion during a time period but no discharge at all, that is gridlock.  It only applies to a small subset of links and time periods.

```
np.argwhere(np.isnan(r.link_costs)
```

only generates four such instances for me, so you can easily do your analysis and omit these values.
I may release a patch for this later today/ this week.

Your scenario seems to overload the network much more in the evening so it's not surprising that you do not see a morning peak. We do not compute pre-saturation delays, meaning that if the link flow values are below capacity there will be free flow travel times, compliant with first order theory.

A warning of sorts:
Your scenario loads a lot of demand with severe spillback for the evening peak, Dynamic Assignment Routines do not fare well under those conditions. Demand that is taken from Static Models cannot simply be applied to a dynamic one, capacity is a hard constraint here.
If you want to gain more intuition with DTAs, and our i-ltm in particular, I'd recommend you start with a smaller examples (fewer time steps, od matrices etc) to check what works and what doesn't. The computation times that you will get will also be much more manageable.

I've written some docs on expectations regarding the DTA implementation here: https://dyntapy.readthedocs.io/en/latest/source/dyntapy.html#dynamic-assignments-known-pitfalls you may need to clear your browser cache before you can see it.

Hope this helps!

**Comment by zhilee2019** [comment] 2022-08-23 01:57
Hi Paul:

Thank you for responing! That makes sense if it is only first order LWR model.  I will change my demand model to avoid overloading. 

Best 
Zhi

**Comment by p-ortmann** [comment] 2022-08-23 08:40
The gridlick error was resolved here: https://github.com/p-ortmann/dyntapy/commit/9468f0cbc4cab7c688c173e1cee707fe6faad534 . Closing this for now.

**Closed by p-ortmann** 2022-08-23 08:40 UTC
